
env:
  node: true
  browser: true
  es2021: true

overrides: []

parserOptions:
  ecmaVersion: latest
  sourceType: module

extedns:
  -'airbnb-base'

rules:
  no-console: 0
  import/extensions: nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
